schema_version = "1.0.0"
id = "flumen"
version = "0.0.2"
name = "Flumen"
tagline = "Procedural surface drainage paths with Geometry Nodes"
maintainer = "Alan Syarif"
type = "add-on"
tags = ["Geometry Nodes"]
blender_version_min = "5.2.0"
license = ["SPDX:MIT"]
